language: java

services:
   - mongodb

jdk:
  - oraclejdk8
  
after_success:
- mkdir -p target/upload
- cp target/service-episode-*-SNAPSHOT.jar target/upload/service-episode.jar
- codecov
deploy:
  provider: s3
  access_key_id: $S3_KEY
  secret_access_key: $S3_SECRET
  bucket: tilosdeploy
  acl: public_read
  local_dir: target/upload
  skip_cleanup: true
before_install:
  - pip install --user codecov


