apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: backend
  name: backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      component: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: backend
    spec:
      containers:
      - command:
        - java
        - -jar
        - /home/tilos/backend.jar
        - --spring.config.location=file:/etc/tilos/tilos.properties
        image: quay.io/tilosradio/backend@sha256:f89f529dd0c178a315091d96702a0f5099cdbd2552e9729a28746a0db63ba7cf
#        image: quay.io/tilosradio/backend@sha256:7eaa86c6ea43814589c0f9d5efd46c04df45a8cb18a3542bd2d121be543d167f
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 9150
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /etc/tilos
          name: config
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: tilos
        name: config
